version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  build:
    commands:
      - echo Build started on `date`
      - chmod -R 755 .
      - mvn test -Dcucumber.options="--tags '@createBookingDataTable'"
      - echo Build completed on `date`


  post_build:
    commands:
      - echo Deploy completed on `date`

